import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
    return useContext(LanguageContext);
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');

    useEffect(() => {
        localStorage.setItem('language', 'en');
        // Update html lang attribute
        document.documentElement.lang = 'en';
    }, []);

    const translations = {
        // Keep English translations for fallback/reference if needed, or simplify to just return key
        // For now, we will simplify to just return the key or English value if present, 
        // but since we are removing Tamil, we can just return the English string directly 
        // or keep the structure if we want to support other languages later.
        // The user asked to "remove all the tamils", so we will remove the 'ta' keys.
        'Home': { en: 'Home' },
        'Store': { en: 'Store' },
        'Orders': { en: 'Orders' },
        'Profile': { en: 'Profile' },
        'Cart': { en: 'Cart' },
        'Checkout': { en: 'Checkout' },
        'Admin': { en: 'Admin' },
        'Categories': { en: 'Categories' },
        'Search': { en: 'Search' },
        'Add to Cart': { en: 'Add to Cart' },
        'Buy Now': { en: 'Buy Now' },
        'Place Order': { en: 'Place Order' },
        'Confirm Order': { en: 'Confirm Order' },
        'Total': { en: 'Total' },
        'Price': { en: 'Price' },
        'Quantity': { en: 'Quantity' },
        'Subtotal': { en: 'Subtotal' },
        'Shipping': { en: 'Shipping' },
        'Tax': { en: 'Tax' },
        'Free': { en: 'Free' },
        'Proceed to Checkout': { en: 'Proceed to Checkout' },
        'Continue Shopping': { en: 'Continue Shopping' },
        'Your cart is empty': { en: 'Your cart is empty' },
        'Start Shopping': { en: 'Start Shopping' },
        'Order Summary': { en: 'Order Summary' },
        'Shipping Address': { en: 'Shipping Address' },
        'Payment Method': { en: 'Payment Method' },
        'Full Name': { en: 'Full Name' },
        'Address': { en: 'Address' },
        'City': { en: 'City' },
        'Pincode': { en: 'Pincode' },
        'Mobile Number': { en: 'Mobile Number' },
        'Back': { en: 'Back' },
        'Back to Cart': { en: 'Back to Cart' },
        'Back to Store': { en: 'Back to Store' },
        'Product not found': { en: 'Product not found' },
        'Return to Store': { en: 'Return to Store' },
        'Find a Store': { en: 'Find a Store' },
        'Visit Store': { en: 'Visit Store' },
        'No stores found': { en: 'No stores found' },
        'Search products...': { en: 'Search products...' },
        'Clear Filters': { en: 'Clear Filters' },
        'All Products': { en: 'All Products' },
        'No products found': { en: 'No products found' },
        'Shop Now': { en: 'Shop Now' },
        'Quick Links': { en: 'Quick Links' },
        'Customer Service': { en: 'Customer Service' },
        'Contact Us': { en: 'Contact Us' },
        'About Us': { en: 'About Us' },
        'Contact': { en: 'Contact' },
        'Privacy Policy': { en: 'Privacy Policy' },
        'Terms': { en: 'Terms' },
        'Privacy': { en: 'Privacy' },
        'Cookies': { en: 'Cookies' },
        'Login': { en: 'Login' },
        'Logout': { en: 'Logout' },
        'My Profile': { en: 'My Profile' },
        'Edit Profile': { en: 'Edit Profile' },
        'Save Changes': { en: 'Save Changes' },
        'Cancel': { en: 'Cancel' },
        'Order History': { en: 'Order History' },
        'Order ID': { en: 'Order ID' },
        'Date': { en: 'Date' },
        'Status': { en: 'Status' },
        'View Details': { en: 'View Details' },
        'Processing': { en: 'Processing' },
        'Shipped': { en: 'Shipped' },
        'Delivered': { en: 'Delivered' },
        'Cancelled': { en: 'Cancelled' },
        'Cash on Delivery': { en: 'Cash on Delivery' },
        'Review Your Order': { en: 'Review Your Order' },
        'Order Placed!': { en: 'Order Placed!' },
        'Order Items': { en: 'Order Items' },
        'Thank you for your purchase. Your order has been confirmed and will be shipped soon.': { en: 'Thank you for your purchase. Your order has been confirmed and will be shipped soon.' },
        'Dashboard': { en: 'Dashboard' },
        'Products': { en: 'Products' },
        'Stores': { en: 'Stores' },
        'News & Offers': { en: 'News & Offers' },
        'Users': { en: 'Users' },
        'Ads Slider': { en: 'Ads Slider' },
        'Admin Panel': { en: 'Admin Panel' },
        'Product Inventory': { en: 'Product Inventory' },
        'Add New Product': { en: 'Add New Product' },
        'Edit Product': { en: 'Edit Product' },
        'View List': { en: 'View List' },
        'Add Product': { en: 'Add Product' },
        'Image': { en: 'Image' },
        'Title': { en: 'Title' },
        'Category': { en: 'Category' },
        'Actions': { en: 'Actions' },
        'Product Title': { en: 'Product Title' },
        'Product Title (Tamil)': { en: 'Product Title (Tamil)' },
        'Description': { en: 'Description' },
        'Description (Tamil)': { en: 'Description (Tamil)' },
        'Main Image': { en: 'Main Image' },
        'Upload Image': { en: 'Upload Image' },
        'Slider Images (Optional)': { en: 'Slider Images (Optional)' },
        'Update Product': { en: 'Update Product' },
        'Store Management': { en: 'Store Management' },
        'Add Store': { en: 'Add Store' },
        'Store Name': { en: 'Store Name' },
        'Store Name (Tamil)': { en: 'Store Name (Tamil)' },
        'Location': { en: 'Location' },
        'Location (Tamil)': { en: 'Location (Tamil)' },
        'Store Image': { en: 'Store Image' },
        'Update Store': { en: 'Update Store' },
        'Manage Products': { en: 'Manage Products' },
        'Add Product to Store': { en: 'Add Product to Store' },
        'News Management': { en: 'News Management' },
        'Add News': { en: 'Add News' },
        'News Title': { en: 'News Title' },
        'News Title (Tamil)': { en: 'News Title (Tamil)' },
        'Type': { en: 'Type' },
        'Content': { en: 'Content' },
        'Content (Tamil)': { en: 'Content (Tamil)' },
        'Order Management': { en: 'Order Management' },
        'User Management': { en: 'User Management' },
        'Ads Management': { en: 'Ads Management' },
        'Select Category': { en: 'Select Category' },
        'Product description...': { en: 'Product description...' },
        'No products found in this store. Add one to get started!': { en: 'No products found in this store. Add one to get started!' },
        'Are you sure you want to delete this product?': { en: 'Are you sure you want to delete this product?' },
        'Product deleted successfully!': { en: 'Product deleted successfully!' },
        'Product updated successfully!': { en: 'Product updated successfully!' },
        'Product uploaded successfully!': { en: 'Product uploaded successfully!' },
        'Store deleted successfully!': { en: 'Store deleted successfully!' },
        'Store updated successfully!': { en: 'Store updated successfully!' },
        'Store added successfully!': { en: 'Store added successfully!' },
        'Product added to store successfully!': { en: 'Product added to store successfully!' },
        'Shop': { en: 'Shop' },
        'FAQ': { en: 'FAQ' },
        'Shipping Policy': { en: 'Shipping Policy' },
        'Returns & Refunds': { en: 'Returns & Refunds' },
        'All rights reserved': { en: 'All rights reserved' },
        'Search by store name or location...': { en: 'Search by store name or location...' },
        'Try adjusting your search terms to find what you\'re looking for.': { en: 'Try adjusting your search terms to find what you\'re looking for.' },
        'Street Address': { en: 'Street Address' },
        'State': { en: 'State' },
        'Country': { en: 'Country' },
        'Including VAT': { en: 'Including VAT' },
        'Back to Edit': { en: 'Back to Edit' },
        'City Name': { en: 'City Name' },
        'John Doe': { en: 'John Doe' },
        '123 Main St': { en: '123 Main St' },
        'Discount': { en: 'Discount' },
        'more items': { en: 'more items' },
        'Total Amount': { en: 'Total Amount' },
        'Card': { en: 'Card' },
        'ending in': { en: 'ending in' },
        'Store Timing': { en: 'Store Timing' },
        'Contact Number': { en: 'Contact Number' },
        'Mobile No': { en: 'Mobile No' },
        'Summer Collection 2024': { en: 'Summer Collection 2024' },
        'Discover the latest trends in fashion.': { en: 'Discover the latest trends in fashion.' },
        'Modern Electronics': { en: 'Modern Electronics' },
        'Upgrade your lifestyle with new tech.': { en: 'Upgrade your lifestyle with new tech.' },
        'Cozy Home Living': { en: 'Cozy Home Living' },
        'Make your home your sanctuary.': { en: 'Make your home your sanctuary.' },
        'Shop the latest trends': { en: 'Shop the latest trends' },
        'Sports': { en: 'Sports' },
        'Toys': { en: 'Toys' },
        'Books': { en: 'Books' },
        'Automotive': { en: 'Automotive' },
        'Manage and track your recent orders': { en: 'Manage and track your recent orders' },
        'Search orders...': { en: 'Search orders...' },
        'Delete Order': { en: 'Delete Order' },
        'Cancel Order': { en: 'Cancel Order' },
        'Are you sure you want to delete this order? This action cannot be undone.': { en: 'Are you sure you want to delete this order? This action cannot be undone.' },
        'Delete': { en: 'Delete' },
        'Headline': { en: 'Headline' },
        'Headline (Tamil)': { en: 'Headline (Tamil)' },
        'Publish News & Offers': { en: 'Publish News & Offers' },
        'Edit Post': { en: 'Edit Post' },
        'Publish': { en: 'Publish' },
        'Update Post': { en: 'Update Post' },
        'Add Post': { en: 'Add Post' },
        'Manage Orders': { en: 'Manage Orders' },
        'Customer': { en: 'Customer' },
        'Pending': { en: 'Pending' },
        'User Database': { en: 'User Database' },
        'Ads Slider Management': { en: 'Ads Slider Management' },
        'Add New Ad Image': { en: 'Add New Ad Image' },
        'Ad Image': { en: 'Ad Image' },
        'Title (Optional)': { en: 'Title (Optional)' },
        'Ad Title': { en: 'Ad Title' },
        'Add': { en: 'Add' },
        'Offer': { en: 'Offer' },
        'News': { en: 'News' },
        'Deal': { en: 'Deal' },
        'All': { en: 'All' },
        'Active': { en: 'Active' },
        'Completed': { en: 'Completed' },
        'Try adjusting your search or filter to find what you\'re looking for.': { en: 'Try adjusting your search or filter to find what you\'re looking for.' },
        'Electronics': { en: 'Electronics' },
        'Fashion': { en: 'Fashion' },
        'Beauty': { en: 'Beauty' },
    };

    const t = (key, field = null) => {
        // Handle data object translation (e.g., t(product, 'title'))
        if (typeof key === 'object' && key !== null && field) {
            return key[field];
        }

        // Handle static label translation
        if (!translations[key]) {
            console.warn(`Translation missing for key: "${key}"`);
            return key;
        }
        return translations[key]['en'] || key;
    };

    const value = {
        language,
        setLanguage,
        t
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
};
